name: Dalfox XSS Scan (demo.testfire.net)

on:
  workflow_dispatch:

jobs:
  dalfox:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dalfox XSS scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/out \
            hahwul/dalfox \
            dalfox url "http://demo.testfire.net/search.jsp?query=test" \
            --format json \
            --output /out/dalfox-result.json

      - name: Upload Dalfox report
        uses: actions/upload-artifact@v4
        with:
          name: dalfox-xss-report
          path: dalfox-result.json
